require "./dsp/version"
require "./dsp/constants"
require "./dsp/verify_value"
require "./dsp/gain"
require "./dsp/scale"

require "./dsp/filtering/fir/*"
require "./dsp/filtering/iir/*"
require "./dsp/interpolation/interpolation"
require "./dsp/resampling/*"
require "./dsp/oscillators/sine_oscillator"
require "./dsp/signal/signal"
require "./dsp/transforms/*"
require "./dsp/windowing/window"
require "./dsp/windowing/windows/*"
require "./dsp/analysis/*"
