require "./splib/version"
require "./splib/constants"
require "./splib/verify_value"
require "./splib/gain"
require "./splib/scale"

require "./splib/filtering/fir/fir_filter"
require "./splib/filtering/fir/sinc_filter"
require "./splib/filtering/fir/dual_sinc_filter"
require "./splib/oscillators/sine_oscillator"
require "./splib/transforms/fft"
require "./splib/windowing/window"
require "./splib/windowing/windows/*"
