require "./splib/*"
require "./splib/oscillators/*"
require "./splib/windowing/window"
require "./splib/windowing/windows/*"
require "./splib/filtering/fir/fir_filter"
require "./splib/filtering/fir/sinc_filter"
require "./splib/transforms/*"
